version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    container_name: swiftList-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: swiftList-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - NODE_ENV=production
